backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "catalogo"
    label: "Catalogo"
    files:
      - name: "prodotti"
        label: "Prodotti"
        file: "products.json"
        fields:
          - label: "Prodotti"
            name: "items"
            widget: "list"
            fields:
              - { label: "Nome", name: "title", widget: "string" }
              - { label: "Descrizione", name: "description", widget: "text" }
              - { label: "Prezzo", name: "price", widget: "string" }
              - { label: "Immagine", name: "image", widget: "image" }
              - { label: "Link Etsy", name: "etsy", widget: "string", required: false }
